### ISSUE TITLE
使用ansibleFATE支持多host部署吗？

### ISSUE THREAD

**Issue by sunyinggang** [FederatedAI/AnsibleFATE#10]
比如在执行命令：
`sh deploy/deploy.sh init -h="10000:192.168.0.1" -g="9999:192.168.1.1" -n=spark`
其中支持`-h="10000:192.168.0.1|10001:192.168.0.2"`这种多host部署吗？
或者说多host部署有其他方案吗或者不支持

**Comment by hqsh** [comment]
同问， @sunyinggang 这个问题有答案了吗？

**Comment by dylan-fan** [comment]
支持
