### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by wforever5620** [FederatedAI/AnsibleFATE#15]
按照文档取部署，mysql用内部的提示连接超时，用外部的有提示找不到mysql命令去连接

**Comment by Yonggie** [comment]
![1d5db393244ed0b7cdf5ba509a73110](https://github.com/FederatedAI/AnsibleFATE/assets/31330044/8917fc1a-dd27-43bc-b492-07cfdb607e88)
请问是这个报错吗？我也遇到了
