### ISSUE TITLE
Deployment by Ansible

### ISSUE THREAD

**Issue by skywd** [FederatedAI/AnsibleFATE#16]
fatal: [ip]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'ip' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).", "unreachable": true}

**Comment by skywd** [comment]
> 
The server supports ssh ip

**Comment by Yonggie** [comment]
要先在每个 target server上都先设置一遍ssh免密登录。他readme里面没写。
