### ISSUE TITLE
通过Ansible部署的FATE平台没有 “flow” 命令

### ISSUE THREAD

**Issue by tigflanker** [FederatedAI/AnsibleFATE#19]
[https://dandelioncloud.cn/article/details/1566946800072617985](url)

↑↑，找到篇很好的文章，成功部署两方FATE，也跑通了纵向LR

但是在模型部署阶段，发现没有flow命令（-bash: flow: 未找到命令）

何解呢？请求、请求

**Comment by zhihuiwan** [comment]
使用前有没有source环境变量？
source /data/projects/fate/bin/init_env.sh

**Comment by tigflanker** [comment]
@zhihuiwan 感谢回复，最终找到了端倪。
因为我一开始是用Ansible安装的，一台机器执行、另一台机器躺平。我昨天是在躺平机执行的flow命令未遂。
解决方案就是重补一下pip install fate-client，成了
