### ISSUE TITLE
deploy/deploy.sh: 10: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by ZuoGuocai** [FederatedAI/AnsibleFATE#3]
When I deploy `AnsibleFATE-1.7.0-release-offline` as  wiki  referfence (https://github.com/FederatedAI/AnsibleFATE/blob/main/docs/ansible_deploy_three_sides.md),
I suck into troube  in the first step. I wonder why, I need help.
```
sh deploy/deploy.sh init -h="10000:10.240.16.38" -g="9999:10.240.16.39" -e="10.240.16.40" -k="host|exchange"
deploy/deploy.sh: 10: Syntax error: "(" unexpected
```

**Comment by or0or1** [comment]
@ZuoGuocai Apologies for the delay。

when  I copy your command and commit it。 Erverything is ok。 

If your shell is bash ？ Can you  show me  outpu informations more？ 

```
ls -l /bin/sh 

sh -x  deploy/deploy.sh init -h="10000:10.240.16.38" -g="9999:10.240.16.39" -e="10.240.16.40" -k="host|exchange"
```

Thanks  you very much.

**Comment by licy666** [comment]
Your shell maybe dash. Change it to the bash.
