### ISSUE TITLE
安装失败/bin/bash deploy/deploy.sh deploy  报错archive. Command \"/usr/bin/gtar\

### ISSUE THREAD

**Issue by caihy05** [FederatedAI/AnsibleFATE#5]
执行报错
#  /bin/bash deploy/deploy.sh deploy
-------------------1 get base data--------------------------------
deploy in progress, please check the log in /root/AnsibleFATE/deploy/../logs/deploy-1645251940.log
                            or commit "tail -f  /root/AnsibleFATE/deploy/../logs/deploy-1645251940.log"
[root@ip-172-31-2-212 AnsibleFATE]# tail -f  /root/AnsibleFATE/deploy/../logs/deploy-1645251940.log
TASK [check : untar(deploy): deploy.tar.gz] ************************************
fatal: [172.31.0.87]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/root/.ansible/tmp/ansible-tmp-1645251944.9-18521-127955827148116/source\". Make sure the required command to extract the file is installed. Command \"/usr/bin/unzip\" could not handle archive. Command \"/usr/bin/gtar\" could not handle archive."}
fatal: [172.31.2.212]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/root/.ansible/tmp/ansible-tmp-1645251944.92-18523-257278277195642/source\". Make sure the required command to extract the file is installed. Command \"/usr/bin/unzip\" could not handle archive. Command \"/usr/bin/gtar\" could not handle archive."}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
172.31.0.87                : ok=4    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   
172.31.2.212               : ok=4    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

检测主机存在/usr/bin/gtar、/usr/bin/unzip

建议copy、实现呢
- copy:
    src: /源目录/1.tar.gz
    dest: /目的目录/1.tar.gz
- shell: gunzip /目的目录/tar.gz

**Comment by caihy05** [comment]
最近在学习fate，辛苦帮忙看一下

**Comment by or0or1** [comment]
你的是什么系统？ 

centos下unzip对应的包是unzip， gtar对应的包是tar。 所以可以先安装一下：
```
yum -y install unzip tar
```

后续我也把这2个依赖加入base模块进行安装。
感谢！！！

**Comment by caihy05** [comment]
@or0or1 感谢
